# catalog/apis/hello-world-api.yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: hello-world-api
  description: A simple Hello World API that returns a greeting message.
spec:
  type: openapi
  lifecycle: experimental
  owner: rahul.raj@talentica.com
  definition: |
    openapi: 3.0.0
    info:
      title: Hello World API
      version: '1.0.0'
    servers:
      - url: http://localhost:7008/api/hello-world
    components:
      securitySchemes:
        bearerAuth:
          type: http
          scheme: bearer
          bearerFormat: JWT  # Optional - specifies the token format (JWT in this case)
    security:
      - bearerAuth: []  # Apply JWT authentication globally to all paths
    paths:
      /hello:
        get:
          summary: Returns a greeting message
          responses:
            '200':
              description: A greeting message
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                        example: Hello, World!
