apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cat-facts-api-v2  # Updated name to make it unique
  description: Cat Facts API Version 2
  tags:
    - cat-facts
    - openapi
  annotations:
    backstage.io/version: "v2"
    backstage.io/system: "cat-facts"
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition: |
    openapi: 3.0.0
    info:
      title: Cat Facts API v2
      version: 2.0.0
    paths:
      /facts:
        get:
          summary: Get a list of cat facts
          responses:
            '200':
              description: A list of cat facts
    servers:
      - url: https://catfact.ninja
