apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-graphql-api
spec:
  type: graphql
  lifecycle: experimental
  owner: rahul.raj@talentica.com
  definition: |
    type Query {
      getUser(id: ID!): User
    }

    type User {
      id: ID!
      name: String!
      email: String!
    }
