apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cat-facts-api
  description: A sample API that provides cat facts.
  tags:
    - demo-api
    - cat-facts
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: development
  owner: rahul.raj@talentica.com
  definition: |
    openapi: "3.0.1"
    info:
      title: Cat Facts API
      version: "1.0"
      description: API to get random cat facts.
    servers:
      - url: https://catfact.ninja
        description: Production Server

    # Define security schemes (API Key in header for PAT)
    components:
      securitySchemes:
        ApiKeyAuth:
          type: apiKey
          in: header
          name: Authorization  # Use the 'Authorization' header to pass the token

      schemas:
        CatFact:
          type: object
          properties:
            fact:
              type: string
            length:
              type: integer

    # Apply security globally (for all paths)
    security:
      - ApiKeyAuth: []

    paths:
      /fact:
        get:
          tags:
            - CatFacts
          operationId: GetRandomCatFact
          summary: Retrieve a random cat fact
          responses:
            '200':
              description: A random cat fact
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/CatFact"
