apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-demo-web
  description: A sample API that provides weather forecast information.
  backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: development
  owner: rahul.raj@talentica.com
  definition: 
    $text: https://gist.githubusercontent.com/lenage/08964335de9064540c8c335fb849c5da/raw/6d63e3546897356882ed7e30cd48891a24e2b354/feature.swagger.json
