# Version 1 of the Weather Forecast API
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weather-forecast-v1
  description: Weather Forecast API Version 1
  tags:
    - weather
    - forecast
  owner: rahul.raj@talentica.com  # Owner in metadata
spec:
  type: openapi
  lifecycle: stable
  owner: rahul.raj@talentica.com  # Owner in spec
  system: weather-system
  version: '1.0.0'  # Version field added
  definition: ./openapi-v1.yaml  # Path to OpenAPI specification for v1

---
# Version 2 of the Weather Forecast API
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weather-forecast-v2
  description: Weather Forecast API Version 2 with extended data and new endpoints
  tags:
    - weather
    - forecast
    - new-version
  owner: rahul.raj@talentica.com  # Owner in metadata
spec:
  type: openapi
  lifecycle: experimental
  owner: rahul.raj@talentica.com  # Owner in spec
  system: weather-system
  version: '2.0.0'  # Version field added
  definition: ./openapi-v2.yaml  # Path to OpenAPI specification for v2
